import { RolePermissions, UserRole } from "@/types";

export const DEFAULT_PERMISSIONS: Record<UserRole, RolePermissions> = {
  FOUNDER: {
    clients: { view: true, create: true, edit: true, delete: true, approve: true },
    leads: { view: true, create: true, edit: true, delete: true },
    projects: { view: true, create: true, edit: true, delete: true, approve: true },
    tasks: { view: true, create: true, edit: true, delete: true },
    employees: { view: true, create: true, edit: true, delete: true },
    hr: { view: true, create: true, edit: true, delete: true, approve: true },
    finance: { view: true, create: true, edit: true, delete: true, approve: true },
    settings: { view: true, create: true, edit: true, delete: true },
    clientPortal: { view: true, create: true, edit: true, delete: true },
  },
  MASTER_ADMIN: {
    clients: { view: true, create: true, edit: true, delete: true, approve: true },
    leads: { view: true, create: true, edit: true, delete: true },
    projects: { view: true, create: true, edit: true, delete: true, approve: true },
    tasks: { view: true, create: true, edit: true, delete: true },
    employees: { view: true, create: true, edit: true, delete: true },
    hr: { view: true, create: true, edit: true, delete: true, approve: true },
    finance: { view: true, create: true, edit: true, delete: false },
    settings: { view: true, create: true, edit: true, delete: true },
    clientPortal: { view: true, create: true, edit: true, delete: false },
  },
  HR: {
    clients: { view: true, create: false, edit: false, delete: false },
    leads: { view: false, create: false, edit: false, delete: false },
    projects: { view: true, create: false, edit: false, delete: false },
    tasks: { view: true, create: true, edit: true, delete: false },
    employees: { view: true, create: true, edit: true, delete: false },
    hr: { view: true, create: true, edit: true, delete: false, approve: true },
    finance: { view: true, create: false, edit: true, delete: false, approve: true }, // Salary slip / reimbursement reviews
    settings: { view: false, create: false, edit: false, delete: false },
    clientPortal: { view: false, create: false, edit: false, delete: false },
  },
  BDM: {
    clients: { view: true, create: true, edit: true, delete: false },
    leads: { view: true, create: true, edit: true, delete: true },
    projects: { view: true, create: false, edit: false, delete: false },
    tasks: { view: true, create: true, edit: true, delete: false },
    employees: { view: true, create: false, edit: false, delete: false },
    hr: { view: false, create: false, edit: false, delete: false },
    finance: { view: true, create: true, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    clientPortal: { view: false, create: false, edit: false, delete: false },
  },
  ACCOUNT_MANAGER: {
    clients: { view: true, create: true, edit: true, delete: false },
    leads: { view: true, create: true, edit: true, delete: false },
    projects: { view: true, create: true, edit: true, delete: false },
    tasks: { view: true, create: true, edit: true, delete: false },
    employees: { view: true, create: false, edit: false, delete: false },
    hr: { view: false, create: false, edit: false, delete: false },
    finance: { view: true, create: true, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    clientPortal: { view: true, create: true, edit: true, delete: false },
  },
  PROJECT_MANAGER: {
    clients: { view: true, create: false, edit: false, delete: false },
    leads: { view: false, create: false, edit: false, delete: false },
    projects: { view: true, create: true, edit: true, delete: true, approve: true },
    tasks: { view: true, create: true, edit: true, delete: true },
    employees: { view: true, create: false, edit: false, delete: false },
    hr: { view: false, create: false, edit: false, delete: false },
    finance: { view: true, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    clientPortal: { view: true, create: true, edit: true, delete: false },
  },
  EMPLOYEE: {
    clients: { view: false, create: false, edit: false, delete: false },
    leads: { view: false, create: false, edit: false, delete: false },
    projects: { view: true, create: false, edit: false, delete: false },
    tasks: { view: true, create: true, edit: true, delete: false },
    employees: { view: true, create: false, edit: false, delete: false },
    hr: { view: true, create: false, edit: false, delete: false },
    finance: { view: true, create: true, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    clientPortal: { view: false, create: false, edit: false, delete: false },
  },
  FINANCE: {
    clients: { view: true, create: false, edit: true, delete: false },
    leads: { view: true, create: false, edit: false, delete: false },
    projects: { view: true, create: false, edit: false, delete: false },
    tasks: { view: true, create: false, edit: false, delete: false },
    employees: { view: true, create: false, edit: false, delete: false },
    hr: { view: true, create: false, edit: false, delete: false },
    finance: { view: true, create: true, edit: true, delete: true, approve: true },
    settings: { view: false, create: false, edit: false, delete: false },
    clientPortal: { view: false, create: false, edit: false, delete: false },
  },
  TEAM_LEAD: {
    clients: { view: true, create: false, edit: false, delete: false },
    leads: { view: false, create: false, edit: false, delete: false },
    projects: { view: true, create: true, edit: true, delete: false },
    tasks: { view: true, create: true, edit: true, delete: true, approve: true },
    employees: { view: true, create: false, edit: false, delete: false },
    hr: { view: true, create: false, edit: false, delete: false },
    finance: { view: false, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    clientPortal: { view: false, create: false, edit: false, delete: false },
  },
  CLIENT: {
    clients: { view: false, create: false, edit: false, delete: false },
    leads: { view: false, create: false, edit: false, delete: false },
    projects: { view: false, create: false, edit: false, delete: false },
    tasks: { view: false, create: false, edit: false, delete: false },
    employees: { view: false, create: false, edit: false, delete: false },
    hr: { view: false, create: false, edit: false, delete: false },
    finance: { view: false, create: false, edit: false, delete: false },
    settings: { view: false, create: false, edit: false, delete: false },
    clientPortal: { view: true, create: true, edit: true, delete: false, approve: true },
  },
};

export const ROLE_LABELS: Record<UserRole, string> = {
  FOUNDER: "Founder & CEO",
  MASTER_ADMIN: "Master Admin",
  HR: "Head of HR",
  BDM: "BDM / Sales Lead",
  ACCOUNT_MANAGER: "Account Manager",
  PROJECT_MANAGER: "Project Manager",
  EMPLOYEE: "Employee / Specialist",
  FINANCE: "Finance & Accounts",
  TEAM_LEAD: "Creative Team Lead",
  CLIENT: "Client (UrbanNest Realty)",
};
